// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Am adăugat -r dotenv/config pentru ca ts-node să citească variabilele de mediu înainte de pornire
    seed: "npx ts-node -r dotenv/config -O {\"module\":\"commonjs\"} prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
